#!/bin/bash

current_dir=$(pwd)
len=${#current_dir}
expected_value="test_env"
current_value=${current_dir:$len-8:8}

if [ "$current_value" == "$expected_value" ]

    then

        docker stop php-sdsdb
        docker stop mysql-sdsdb
        docker container prune -f
        docker run --name=mysql-sdsdb -d --env="MYSQL_ROOT_PASSWORD=lolk1234" vsamov/mysql-5.1.73
        ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql-sdsdb)
        sleep 5
        mysql -uroot -plolk1234 -h $ip -P 3306 < sdsdb.sql
        source_dir=${current_dir:0:$len-9}
        docker run --name=php-sdsdb -d -p 8080:80 -v $source_dir:/var/www/html --link mysql-sdsdb:vsamov/mysql-5.1.73 nimmis/apache-php5
        sleep 10
        docker exec php-sdsdb touch /var/www/html/mysql.log
        docker exec php-sdsdb chmod 0777 /var/www/html/mysql.log

    else

        echo "ERROR: can't execute devops script - make sure you cd into the .../test_env/ folder"

fi