#!/bin/bash

current_dir=$(pwd)
len=${#current_dir}
expected_value="test_env"
current_value=${current_dir:$len-8:8}

if [ "$current_value" == "$expected_value" ]

    then

        docker stop php-sdsdb
        docker stop mysql-sdsdb
        docker stop mysql-test-sdsdb
        docker container prune -f
        docker run --name=mysql-sdsdb -p 33060:3306 -d --env="MYSQL_ROOT_PASSWORD=lolk1234" mariadb:10.0.33
	docker run --name=mysql-test-sdsdb -p 33061:3306 -d --env="MYSQL_ROOT_PASSWORD=lolk1234" mariadb:10.0.33
	sleep 12
        	
	source ./reset_test_db
        ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql-sdsdb)
        docker exec -i mysql-sdsdb mysql -uroot -plolk1234 < sdsdb.sql
        docker exec -i mysql-sdsdb mysql -uroot -plolk1234 < additionnal_migrations.sql

        source_dir=${current_dir:0:$len-9}
        docker run --name=php-sdsdb -d -w "/var/www/html/" -p 8080:80 -v $source_dir:/var/www/html --link mysql-sdsdb:dev_db --link mysql-test-sdsdb:test_db jtbai/php5-phpunit
        sleep 5
        docker exec php-sdsdb touch /var/www/html/mysql.log
        docker exec php-sdsdb chmod 0777 /var/www/html/mysql.log

    else

        echo "ERROR: can't execute devops script - make sure you cd into the .../test_env/ folder"

fi
