ALTER TABLE  `inspection` ADD  `Chaloupe` TINYINT NOT NULL ,
ADD  `ChaloupeRame` TINYINT NOT NULL ,
ADD  `ChaloupeAncre` TINYINT NOT NULL ,
ADD  `ChaloupeGilets` TINYINT NOT NULL ,
ADD  `ChaloupeBouee` TINYINT NOT NULL ,
ADD  `LigneBouee` TINYINT NOT NULL ,
ADD  `BoueeProfond` TINYINT NOT NULL ,
ADD  `Canotage` TINYINT NOT NULL ,
ADD  `HeureSurveillance` TINYINT NOT NULL ,
ADD  `LimitePlage` TINYINT NOT NULL ,
ADD  `LongueurPlage` TINYINT NOT NULL ,
ADD  `NBPreposes` TINYINT NOT NULL ;